### ISSUE TITLE
No Http server

### ISSUE THREAD

**Issue by nickm324** [loginov-rocks/ESP8266-Arduino-PlatformIO#1]
Followed instructions to the letter and I can see it say connected and list an IP, but when trying to pull it up in a browser the connection is always refused and no AP ever shows up on my phone. Is there some code missing or something?

**Comment by loginov-rocks** [comment]
What's your output in a serial monitor?

**Comment by nickm324** [comment]
Miniterm on COM4  9600,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
��*WM:
*WM: AutoConnect
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result:
*WM: 3
*WM: IP Address:
*WM: 192.168.0.46
Connected!
*WM: freeing allocated params!
Idle...
Idle...
Idle...
Idle...
Idle...
Idle...
Idle...
Idle...

**Comment by nickm324** [comment]
Never see it say anything about starting HTTP server.

**Comment by nickm324** [comment]
If I temporarily turn off my router wifi  so the it can't connect I get this.
AutoConnect
*WM: Connecting as wifi client...
*WM: Using last saved values, should be faster
*WM: Connection result:
*WM: 1
*WM:
*WM: Configuring access point...
*WM: NodeMCU-Arduino-PlatformIO
*WM: AP IP address:
*WM: 192.168.4.1
*WM: HTTP server started

**Comment by loginov-rocks** [comment]
Alright, it uses previous connection credentials, if you want to start AP on each device launch, use `wifiManager.resetSettings();` more info on Wi Fi Manager here https://github.com/tzapu/WiFiManager
